sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Denver

# Files to exclude from build
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock

# Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate-v2
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jemoji

# Gem settings
pagination: 
  debug: false
  collection: 'posts'
  per_page: 5 # jekyll-paginate-v2 > items per page
  permalink: '/page/:num' # jekyll-paginate-v2 > blog page
  limit: 0 # Limit how many pagenated pages to create (default: 0, means all)
  sort_field: 'date' # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: hpquintana_dev # jekyll-seo-tag > Owners twitter username
author: Hector Quintana # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Hector Quintana # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/hpquintana_dev
    - https://github.com/hpquintana

  # 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: Noah # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Site description" # Site description and default description, also used in jekyll-seo-tag
url: "hpquintana.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/daviddarnes/alembic"
email: "hector.quintana.dev@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://pbs.twimg.com/profile_images/830090298214658049/-DVdkGBN_400x400.jpg" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: false # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /blog/
  Categories: /categories/
  Search: /search/
  About: /about/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/hpquintana_dev
  # LinkedIn: https://www.linkedin.com/in/daviddarnes
  # Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/hpquintana

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""

collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    #description: "My thoughts and ideas" # The post list page content
    feature_text: "Dream On"
    feature_image: /assets/img/gallery/main.jpeg
    feature_url: https://youtu.be/3-2u2lhGO4w
  work:
    title: Previous Work
    output: true
